import type { Metadata } from "next";
import "./globals.css";
import styles from "./layout.module.css";
import "@mantine/core/styles.css";
import { MantineProvider } from "@mantine/core";

export const metadata: Metadata = {
  title: "App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MantineProvider>
          <nav className={styles.nav}>Oddoro</nav>
          {children}
          <footer className={styles.footer}>Bye</footer>
        </MantineProvider>
      </body>
    </html>
  );
}
