export const oddsApiTeamNameMap: Record<string, string> = {
  // Bundesliga
  "Bayern Munich": "FC Bayern München",
  "Bayer Leverkusen": "Bayer 04 Leverkusen",
  "Borussia Dortmund": "Borussia Dortmund",
  "RB Leipzig": "RB Leipzig",
  "Eintracht Frankfurt": "Eintracht Frankfurt",
  "SC Freiburg": "SC Freiburg",
  Mainz: "1. FSV Mainz 05",
  "FSV Mainz 05": "1. FSV Mainz 05",
  "Werder Bremen": "SV Werder Bremen",
  "VfB Stuttgart": "VfB Stuttgart",
  "Union Berlin": "1. FC Union Berlin",
  "Borussia Monchengladbach": "Borussia Mönchengladbach",
  "Borussia Mönchengladbach": "Borussia Mönchengladbach",
  Augsburg: "FC Augsburg",
  "FC Augsburg": "FC Augsburg",
  Wolfsburg: "VfL Wolfsburg",
  "VfL Wolfsburg": "VfL Wolfsburg",
  Hoffenheim: "TSG Hoffenheim",
  "TSG Hoffenheim": "TSG Hoffenheim",
  "St Pauli": "FC St. Pauli",
  "FC St Pauli": "FC St. Pauli",
  "FC St. Pauli": "FC St. Pauli",
  Heidenheim: "1. FC Heidenheim 1846",
  "FC Heidenheim": "1. FC Heidenheim 1846",
  "Hamburger SV": "Hamburger SV",
  Hamburg: "Hamburger SV",
  "FC Cologne": "1. FC Köln",
  Koln: "1. FC Köln",
  Köln: "1. FC Köln",

  // 2. Bundesliga
  Schalke: "FC Schalke 04",
  "Schalke 04": "FC Schalke 04",
  "Hertha Berlin": "Hertha BSC",
  "Hertha BSC": "Hertha BSC",
  "Hannover 96": "Hannover 96",
  "Fortuna Dusseldorf": "Fortuna Düsseldorf",
  "Fortuna Düsseldorf": "Fortuna Düsseldorf",
  Darmstadt: "SV Darmstadt 98",
  "Darmstadt 98": "SV Darmstadt 98",
  "Holstein Kiel": "Holstein Kiel",
  "VfL Bochum": "VfL Bochum",
  Bochum: "VfL Bochum",
  "Karlsruher SC": "Karlsruher SC",
  Kaiserslautern: "1. FC Kaiserslautern",
  "FC Kaiserslautern": "1. FC Kaiserslautern",
  Nurnberg: "1. FC Nürnberg",
  Nürnberg: "1. FC Nürnberg",
  "FC Nurnberg": "1. FC Nürnberg",
  Paderborn: "SC Paderborn 07",
  "SC Paderborn": "SC Paderborn 07",
  Magdeburg: "1. FC Magdeburg",
  "FC Magdeburg": "1. FC Magdeburg",
  Elversberg: "SV 07 Elversberg",
  "SV Elversberg": "SV 07 Elversberg",
  "Greuther Furth": "SpVgg Greuther Fürth",
  "Greuther Fürth": "SpVgg Greuther Fürth",
  "Eintracht Braunschweig": "Eintracht Braunschweig",
  Braunschweig: "Eintracht Braunschweig",
  "Preussen Munster": "Preußen Münster",
  "Preußen Münster": "Preußen Münster",
  "Arminia Bielefeld": "Arminia Bielefeld",
  "Dynamo Dresden": "Dynamo Dresden",
};
